// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlM-YBVrJb_h1yIEfucSngON2jt49L3qo',
    appId: '1:17486696625:web:d3bd7782705e61fd2bd290',
    messagingSenderId: '17486696625',
    projectId: 'crypto-app-a73ea',
    authDomain: 'crypto-app-a73ea.firebaseapp.com',
    storageBucket: 'crypto-app-a73ea.firebasestorage.app',
    measurementId: 'G-X2QF6SSPDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENQ7n8hqjXOqzW17HtbK0pFj0EuOoDps',
    appId: '1:17486696625:android:b5774ba9a7f33d1c2bd290',
    messagingSenderId: '17486696625',
    projectId: 'crypto-app-a73ea',
    storageBucket: 'crypto-app-a73ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTy1aOssA6H0DNFSpWjbit7xhSqM87d0',
    appId: '1:17486696625:ios:300d631d96dfe7fb2bd290',
    messagingSenderId: '17486696625',
    projectId: 'crypto-app-a73ea',
    storageBucket: 'crypto-app-a73ea.firebasestorage.app',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlM-YBVrJb_h1yIEfucSngON2jt49L3qo',
    appId: '1:17486696625:web:8bc343c16664d9cd2bd290',
    messagingSenderId: '17486696625',
    projectId: 'crypto-app-a73ea',
    authDomain: 'crypto-app-a73ea.firebaseapp.com',
    storageBucket: 'crypto-app-a73ea.firebasestorage.app',
    measurementId: 'G-Z4H6G92D1Y',
  );
}
