// Generated by Hive CE
// Do not modify
// Check in to version control

// ignore: depend_on_referenced_packages
import 'package:hive_ce/hive.dart';
import 'package:crypto_app/repositories/crypto_coins/models/crypto_coin.dart';
import 'package:crypto_app/repositories/crypto_coins/models/crypto_coin_details.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailAdapter());
  }
}
